# Generated by Django 2.0.6 on 2018-08-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_name', models.CharField(max_length=255)),
                ('cd_url', models.URLField(blank=True, max_length=255)),
                ('release_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Circle_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=255)),
                ('circle_url', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lyric_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Original_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Original_song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Original_work_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_work_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Cd')),
            ],
        ),
        migrations.CreateModel(
            name='Song_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Arrange_master')),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Lyric_master')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Vocal_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocal_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='song_info',
            name='vocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Vocal_master'),
        ),
        migrations.AddField(
            model_name='original_song',
            name='original_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Original_work_master'),
        ),
        migrations.AddField(
            model_name='original_info',
            name='original_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Original_song'),
        ),
        migrations.AddField(
            model_name='original_info',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Song'),
        ),
        migrations.AddField(
            model_name='cd',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tohocd.Circle_master'),
        ),
    ]
