# Generated by Django 2.0.6 on 2018-09-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tohocd', '0002_auto_20180925_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_info',
            name='arrange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tohocd.Arrange_master'),
        ),
        migrations.AlterField(
            model_name='song_info',
            name='lyric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tohocd.Lyric_master'),
        ),
        migrations.AlterField(
            model_name='song_info',
            name='vocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tohocd.Vocal_master'),
        ),
    ]
