# Generated by Django 2.0.6 on 2018-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tohocd', '0004_auto_20180925_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='cd_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='circle_master',
            name='circle_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
